### ISSUE TITLE
Error koneksi database

### ISSUE THREAD

**Issue by ivanarrianto** [topyk27/Panjar-Biaya-Perkara#1]
Saat dicoba di localhost, muncul pesan error, sehingga tidak bisa memilih kecamatan, jenis perkara, dll. Kemungkinan gagal koneksi ke database?

![image](https://user-images.githubusercontent.com/78266122/120151202-2c1b7c80-c216-11eb-94d4-96d5941a7981.png)

**Comment by topyk27** [comment]
pakai php versi berapa?

**Comment by ivanarrianto** [comment]
ini masih dicoba di localhost dulu mas
versi php 8.0.3

**Comment by topyk27** [comment]
> ini masih dicoba di localhost dulu mas
> versi php 8.0.3

saya kemarin pakai php 5, silahkan disesuaikan code nya untuk versi php 8

**Comment by isblueb** [comment]
Saya pake php 5.6 muncul pesan error juga sehingga tidak bisa memilih kecamatan, jenis perkara, dll.

**Comment by ivanarrianto** [comment]
saya sudah coba di PHP versi 5 masih belum bisa juga, saya coba pakai parser-php juga tidak bisa mas

**Comment by topyk27** [comment]
buka file `asset/js/index.js`
`var svr = '/panjar_perkara/proses/';`
mungkin salah di sini, `panjar_perkara` diubah dengan nama foldernya jadinya `/panjar-biaya-perkara/proses/`

**Comment by topyk27** [comment]
> saya sudah coba di PHP versi 5 masih belum bisa juga, saya coba pakai parser-php juga tidak bisa mas

buka file `asset/js/index.js`
`var svr = '/panjar_perkara/proses/';`
mungkin salah di sini, `panjar_perkara` diubah dengan nama foldernya jadinya `/panjar-biaya-perkara/proses/`

**Comment by yuliexho** [comment]
permisi mau tanya om, ketika buka di PA tenggarong Panjar-Biaya-Perkara/proses/detail-radius.php itu tulisan succes tapi ketika saya buka di localhost malah keluar tulisan gini, 
Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\Panjar-Biaya-Perkara\proses\koneksi.php:21 Stack trace: #0 C:\xampp\htdocs\Panjar-Biaya-Perkara\proses\koneksi.php(12): DB_CONNECT->connect() #1 C:\xampp\htdocs\Panjar-Biaya-Perkara\proses\detail-radius.php(4): DB_CONNECT->__construct() #2 {main} thrown in C:\xampp\htdocs\Panjar-Biaya-Perkara\proses\koneksi.php on line 21
ada script yg terbaru utk koneksinya tidak om..?

**Comment by topyk27** [comment]
> Uncaught Error: Call to undefined function mysql_connect()

script nya menggunakan php 5, silahkan disesuaikan dengan versi php anda.
