### ISSUE TITLE
tidak bisa pilih kelurahan 

### ISSUE THREAD

**Issue by yuliexho** [topyk27/Panjar-Biaya-Perkara#3]
permisi om, ketika saya habis klik kecamatan pilih kecamatan lgsg ada peringatan halaman bermasalah itu yang salah pada kecamatannya atau pada kelurahannya om..?
mohon pencerahannya om

**Comment by topyk27** [comment]
> permisi om, ketika saya habis klik kecamatan pilih kecamatan lgsg ada peringatan halaman bermasalah itu yang salah pada kecamatannya atau pada kelurahannya om..? mohon pencerahannya om

bisa lampirkan ss nya, dan juga console nya.

**Comment by yuliexho** [comment]
mohon maaf om setelah tak coba berkali-kali sudah bisa dan hasilnya seperti ini, kmren kesalahan saya pada $sql
`<?php 

$response = array();
require_once 'koneksi.php';
$db = new DB_CONNECT();
$db = $db->connect();
if(isset($_POST["id"])){
$id_kecamatan = $_POST["id"];
$sql = "select radius.kelurahan,radius.id,radius.kecamatan,radius.biaya from radius where radius.kecamatan = '$id_kecamatan'";
$kelurahan_result = mysqli_query($db, $sql) or die(mysql_error());
if (mysqli_num_rows($kelurahan_result) > 0) {
	$response['kelurahan'] = array();
	while ($row = mysqli_fetch_array($kelurahan_result)) {
		$kelurahan = array();
		$kelurahan['id'] = $row['id'];
		$kelurahan['kecamatan'] = $row['kecamatan'];
		$kelurahan['kelurahan'] = $row['kelurahan'];
		$kelurahan['biaya'] = $row['biaya'];
		array_push($response['kelurahan'], $kelurahan);
	}
	$response['success'] = 1;
	echo json_encode($response);
}else{
	$response['success'] = 0;
	echo json_encode($response);
}
}else{
	echo "gak di set";
}

 ?>`

**Comment by topyk27** [comment]
> mohon maaf om setelah tak coba berkali-kali sudah bisa dan hasilnya seperti ini, kmren kesalahan saya pada $sql dan hasilnya seperti ini dan mohon kalau boleh minta tolong utk sintak (biaya Pnbp pemberitahuan isi putusan x biaya radiusnya) ![Untitled-1](https://user-images.githubusercontent.com/36599440/158572739-d3b6899c-fddb-487f-a6a0-053b9fa4da72.png)

![a](https://user-images.githubusercontent.com/41628145/158797579-941477c6-1b6a-451e-9fec-b9ce20c057d4.png)
untuk proses perhitungan ada di asset/js/index.js tinggal disesuaikan variable sesuai kebutuhan.

**Comment by putracaniago** [comment]
boleh request aplikasi fullnya? saolnya saya buka gak bisa pilih perkara, seperti tidak terhubung ke database
![11](https://user-images.githubusercontent.com/98021841/159412843-a176eb09-8166-4627-b602-58a91ee6d281.png)

**Comment by yuliexho** [comment]
(https://github.com/topyk27/Panjar-Biaya-Perkara/issues/3#issuecomment-1070805963)

kalau untuk mengambil nilai tertinggi pada tabel biaya pemanggilan si T dan P itu apakah pakai variabel baru atau langsung select..?

**Comment by yuliexho** [comment]
> > mohon maaf om setelah tak coba berkali-kali sudah bisa dan hasilnya seperti ini, kmren kesalahan saya pada $sql dan hasilnya seperti ini dan mohon kalau boleh minta tolong utk sintak (biaya Pnbp pemberitahuan isi putusan x biaya radiusnya) ![Untitled-1](https://user-images.githubusercontent.com/36599440/158572739-d3b6899c-fddb-487f-a6a0-053b9fa4da72.png)
> 
> ![a](https://user-images.githubusercontent.com/41628145/158797579-941477c6-1b6a-451e-9fec-b9ce20c057d4.png) untuk proses perhitungan ada di asset/js/index.js tinggal disesuaikan variable sesuai kebutuhan.

permisi lagi om untuk memilih nilai terbesar di antara 2 tabel biaya pemanggilan gimana caranya..?
